/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.azure.feathr.piper;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void someLibraryMethodReturnsTrue() {
        PiperService classUnderTest = null; // new PiperService();
        // assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
