/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.windoze.feathr.piper;

import org.junit.Test;

public class LibraryTest {


    static Object inc(Object arg) {
        Long n = (Long) arg;
        return n + 42;
    }

    static Object dec(Object arg) {
        Long n = (Long) arg;
        return n - 42;
    }

    @Test
    public void someLibraryMethodReturnsTrue() {
        Function1 f = LibraryTest::inc;
        UdfRepository repo = new UdfRepository()
                .put("inc", (Function1) LibraryTest::inc)
                .put("dec", (Function1) LibraryTest::dec);
        try (PiperService svc = new PiperService("t(x) | project y=inc(x), z=dec(x);", "", repo)) {
            new Thread(() -> {
                svc.start("localhost", (short) 8000);
            }).start();
            Thread.sleep(5 * 1000);
            svc.stop();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
